Cora:
  ntrials: 1
  sparse: 0
  epochs: 300
  cl_batch_size: 0
  nlayers_proj: 1
  alpha: 0.5
  k: 20
  maskfeat_rate_1: 0.8
  maskfeat_rate_2: 0.1
  dropedge_rate_1: 0.8
  dropedge_rate_2: 0.8
  lr_disc: 0.001
  margin_hom: 0.5
  margin_het: 0.5
  cl_rounds: 2
  eval_freq: 5
CiteSeer:
  ntrials: 5
  sparse: 0
  epochs: 400
  cl_batch_size: 0
  nlayers_proj: 2
  alpha: 0.1
  k: 30
  maskfeat_rate_1: 0.1
  maskfeat_rate_2: 0.1
  dropedge_rate_1: 0.8
  dropedge_rate_2: 0.1
  lr_disc: 0.001
  margin_hom: 0.5
  margin_het: 0.5
  cl_rounds: 2
  eval_freq: 5
PubMed:
  ntrials: 10
  sparse: 1
  epochs: 800
  cl_batch_size: 5000
  nlayers_proj: 2
  alpha: 0.1
  k: 0
  maskfeat_rate_1: 0.1
  maskfeat_rate_2: 0.5
  dropedge_rate_1: 0.5
  dropedge_rate_2: 0.1
  lr_disc: 0.001
  margin_hom: 0.5
  margin_het: 0.5
  cl_rounds: 2
  eval_freq: 20
DBLP:
  ntrials: 5
  sparse: 1
  epochs: 800
  cl_batch_size: 5000
  nlayers_proj: 2
  alpha: 0.1
  k: 0
  maskfeat_rate_1: 0.1
  maskfeat_rate_2: 0.5
  dropedge_rate_1: 0.5
  dropedge_rate_2: 0.1
  lr_disc: 0.001
  margin_hom: 0.5
  margin_het: 0.5
  cl_rounds: 2
  eval_freq: 20